# Generated by Django 3.1.5 on 2021-04-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('head0', models.CharField(default='', max_length=500)),
                ('head1', models.CharField(default='', max_length=500)),
                ('head2', models.CharField(default='', max_length=500)),
                ('head3', models.CharField(default='', max_length=500)),
                ('head4', models.CharField(default='', max_length=500)),
                ('thumbnail', models.ImageField(default='', upload_to='lol/images')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
