# Generated by Django 3.1.5 on 2021-04-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0009_auto_20210425_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
